### ISSUE TITLE
您好，导入后就无法编辑邀请函了。

### ISSUE THREAD

**Issue by ankylau** [imlinhanchao/invitation-card-maker#1]
浏览器控制台报错
[TypeError: (this.variables || [[""]])[0].map is not a function]    ---vue.min.js:11 

 Uncaught TypeError: (this.variables[index] || []).map is not a function  ----do.js:246
    at drawQr (do.js:246:120)
    at drawImgDone (do.js:252:21)
    at drawImgs (do.js:256:53)
    at do.js:263:21
    at image.onload (do.js:301:27)

**Comment by imlinhanchao** [comment]
已修正，是导出的问题，已经导出的文件需要修改 `variables`，错误内容类似如下：
```json
"variables": [
        {
            "0": "魏华",
            "1": "19:00"
        }
]
```
应该修正为：
```json
"variables": [
    ["魏华", "19:00"]
]
```
